
# Google Assistant Config File - Required to set 'aliases' for device names. Also makes the room setup easier

# Google Home App will take on the name of the first alias if it exists, otherwise it will use the name


switch.basement_stairs:
  name: Basement Stairs Light
  room: Basement
  aliases:
    - Basement Stairs
    - Kitchen Stairs Light
    - Kitchen Stairs

light.basement_storage:
  name: Basement Storage Light
  room: Basement
  aliases:
    - Basement Storage

light.dining_room:
  name: Dining Room Light
  room: Dining Room
  aliases:
    - Dining Room Light
    - Dining Room

switch.kitchen_ceiling:
  name: Kitchen Ceiling Switch
  room: Kitchen
  aliases:
    - Kitchen Ceiling Switch
    - Kitchen Ceiling Switch Light
    - Kitchen Ceiling Light
    - Kitchen Ceiling

light.kitchen_ceiling:
  name: Kitchen Ceiling Light
  room: Kitchen
  aliases:
    - Kitchen Ceiling Light
    - Kitchen Ceiling
    - Kitchen Lights

switch.kitchen_door:
  name: Kitchen Door Light
  room: Kitchen
  aliases:
    - Kitchen Door Light
    - Kitchen Door
    - Kitchen Entryway Light
    - Kitchen Entryway
    - Kitchen Stairs Light
    - Kitchen Stairs

switch.kitchen_closet:
  name: Kitchen Closet Light
  room: Kitchen
  aliases:
    - Kitchen Closet
    - Kitchen Pantry Light
    - Kitchen Pantry
    - Kitchen Pantry Light

light.laundry_room:
  name: Laundry Room Light
  room: Laundry Room
  aliases:
    - Laundry Room Light
    - Laundry Room

# Hue Group
# light.living_room:
#   name: Living Room Light
#   room: Living Room
#   aliases:
#     - Living Room

light.living_room_fan_light:
  name: Living Room Fan Light
  room: Living Room
  aliases:
    - Living Room Fan Light

light.living_room_lamps:
  name: Living Room Lamps
  room: Living Room
  aliases:
    - Living Room Lamps

light.hue_lightstrip_plus_1:
  name: Living Room TV Lightstrip
  room: Living Room
  aliases:
    - Living Room TV Lightstrip
    - Living Room TV Light
    - Living Room TV Lights
    - Living Room Television Lightstrip
    - Living Room Television Light
    - Living Room Television Lights

switch.main_hallway:
  name: Main Hallway Light
  room: Main Hallway
  aliases:
    - Main Hallway Light
    - Main Hallway Ceiling Light

# Hue Group
# light.master_bedroom:
#   name: Master Bedroom Lights
#   room: Master Bedroom
#   aliases:
#     - Kitchen Bedroom Lights

light.master_fan_light:
  name: Master Fan Light
  room: Master Bedroom
  aliases:
    - Master Bedroom Fan Light
    - Master Fan Light

switch.outside_front:
  name: Outside Front Lights
  room: Outside
  aliases:
    - Outside Front Lights
    - Carport Lights
    - Outside Side Lights

light.pantry:
  name: Pantry Light
  room: Pantry
  aliases:
    - Pantry Lights
    - Pantry Light
    - Basement Pantry Light
    - Basement Pantry Lights

light.alex_master_lamp:
  name: Alex Master Lamp
  room: Master Bedroom
  aliases:
    - Alex Master Lamp
    - Alex Master Light
    - Alex Master Bedroom Lamp
    - Alex Master Bedroom Light

light.steph_master_lamp:
  name: Steph Master Lamp
  room: Master Bedroom
  aliases:
    - Steph Master Lamp
    - Steph Master Light
    - Steph Master Bedroom Lamp
    - Steph Master Bedroom Light

light.study_ceiling_light:
  name: Study Ceiling Lights
  room: Study
  aliases:
    - Study Ceiling Lights
    - Study Lights
