
        ##########################################################
        ## Average Household Light Level
        ##########################################################

- platform: min_max
  name: 'Average Light Level'
  type: mean
  round_digits: 2
  entity_ids:
    - sensor.hue_motion_study_2_light_level
    - sensor.hue_motion_study_light_level
    - sensor.hue_motion_kitchen_light_level
    - sensor.hue_motion_master_bedroom_light_level

    # - sensor.living_room_motion_sensor_luminance
    # - sensor.master_bathroom_motion_sensor_luminance
