
        ##########################################################
        ## PWS (via Wunderground Custom Component wundergroundpws)
        ## TRYING OUT NATIVE WUNDERGROUND COMPONENT (wunderground)
        ## Location: Side Deck? (Not installed yet)
        ##########################################################

- platform: wundergroundpws
  api_key: !secret wunderground_api_key
  pws_id: !secret wunderground_pws_id
  monitored_conditions:
    - stationID

    - solarRadiation
    - uv

    - pressure
    
    - humidity
    - dewpt
    - heatIndex
    
    - precipTotal
    - precipRate
    - precip_1d
    - precip_chance_1d

    - temp
    - temp_high_1d
    - temp_low_1d

    - winddir
    - windGust
    - windSpeed
    - windChill
    - wind_1d

    - weather_1d
    - weather_1n






# THIS PLATFORM DOES NOT WORK WITH THE NEW W.U. API - Perhaps it will be updates in the future?

        ##########################################################
        ## PWS (via Wunderground)
        ## Location: Side Deck? (Not installed yet)
        ##########################################################

# - platform: wunderground
#   api_key: !secret wunderground_api_key
#   pws_id: !secret wunderground_pws_id
#   monitored_conditions:
#     - station_id

#     - alerts

#     - solarradiation
#     - UV

#     - pressure_mb

#     - relative_humidity
#     - dewpoint_c
#     - feelslike_c
#     - heat_index_c
    
#     - precip_today_metric     # Total precipitation today so far
#     - precip_1d_mm            # Forecasted precipitation intensity in millimeters
#     - precip_1d               # Forecasted precipitation probability in %

#     - temp_c                  # Current temperature
#     - temp_high_1d_c          # Daytime high
#     - temp_low_1d_c

#     - wind_degrees
#     - wind_kph
#     - wind_1d_kph
#     - wind_gust_kph
#     - wind_gust_1d_kph

#     - weather # A human-readable text summary with picture from Wunderground.
#     - weather_1d_metric # A human-readable weather forecast using metric units.
#     - weather_1n_metric



# POTENTIAL MONITORED_CONDITIONS:

# Config for [sensor.wunderground] must be one of the following:
# [
#   'UV', 'alerts', 

#   'dewpoint_c', 'dewpoint_f', 'dewpoint_string', 

#   'elevation', 'location', 'observation_time', 

#   'feelslike_c', 'feelslike_f', 'feelslike_string', 

#   'heat_index_c', 'heat_index_f', 'heat_index_string', 

#   'precip_1d', 'precip_1d_in', 'precip_1d_mm', 
#   'precip_1hr_in', 'precip_1hr_metric', 'precip_1hr_string', 
#   'precip_2d', 'precip_2d_in', 'precip_2d_mm', 
#   'precip_3d', 'precip_3d_in', 'precip_3d_mm', 
#   'precip_4d', 'precip_4d_in', 'precip_4d_mm', 
#   'precip_today_in', 'precip_today_metric', 'precip_today_string', 

#   'pressure_in', 'pressure_mb', 'pressure_trend', 

#   'relative_humidity', 
#   'solarradiation', 

#   'station_id', 

#   'temp_c', 'temp_f', 
#   'temp_high_1d_c', 'temp_high_1d_f', 
#   'temp_high_2d_c', 'temp_high_2d_f', 
#   'temp_high_3d_c', 'temp_high_3d_f', 
#   'temp_high_4d_c', 'temp_high_4d_f', 
#   'temp_high_avg_c', 'temp_high_avg_f', 
#   'temp_high_record_c', 'temp_high_record_f', 
#   'temp_low_1d_c', 'temp_low_1d_f', 
#   'temp_low_2d_c', 'temp_low_2d_f', 
#   'temp_low_3d_c', 'temp_low_3d_f', 
#   'temp_low_4d_c', 'temp_low_4d_f', 
#   'temp_low_avg_c', 'temp_low_avg_f', 
#   'temp_low_record_c', 'temp_low_record_f', 
#   'temperature_string', 

#   'visibility_km', 'visibility_mi', 

#   'weather', 'weather_10h', 'weather_11h', 'weather_12h', 'weather_13h', 'weather_14h', 'weather_15h', 'weather_16h', 'weather_17h', 'weather_18h', 'weather_19h', 'weather_1d', 'weather_1d_metric', 
#   'weather_1h', 'weather_1n', 'weather_1n_metric', 'weather_20h', 'weather_21h', 'weather_22h', 'weather_23h', 'weather_24h', 'weather_25h', 'weather_26h', 'weather_27h', 'weather_28h', 'weather_29h', 
#   'weather_2d', 'weather_2d_metric', 'weather_2h', 'weather_2n', 'weather_2n_metric', 'weather_30h', 'weather_31h', 'weather_32h', 'weather_33h', 'weather_34h', 'weather_35h', 'weather_36h', 'weather_3d', 
#   'weather_3d_metric', 'weather_3h', 'weather_3n', 'weather_3n_metric', 'weather_4d', 'weather_4d_metric', 'weather_4h', 'weather_4n', 'weather_4n_metric', 'weather_5h', 'weather_6h', 'weather_7h', 
#   'weather_8h', 'weather_9h', 

#   'wind_1d_kph', 'wind_1d_mph', 'wind_2d_kph', 'wind_2d_mph', 'wind_3d_kph', 'wind_3d_mph', 'wind_4d_kph', 'wind_4d_mph', 'wind_degrees', 'wind_dir', 'wind_gust_1d_kph', 'wind_gust_1d_mph', 
#   'wind_gust_2d_kph', 'wind_gust_2d_mph', 'wind_gust_3d_kph', 'wind_gust_3d_mph', 'wind_gust_4d_kph', 'wind_gust_4d_mph', 'wind_gust_kph', 'wind_gust_mph', 'wind_kph', 'wind_mph', 'wind_string'
# ]

