
# This is an example of how to force update Kasa switches so they respond quicker in HA
# Move this to Appdaemon light module once setup

- alias: 'Kasa Switch Update Test'
  trigger:
    - platform: time_pattern
      seconds: '/5'
  action:
    - service: homeassistant.update_entity
      entity_id: 
        - switch.kitchen_ceiling
        - switch.basement_stairs
        - switch.kitchen_closet
        - switch.kitchen_door
        - switch.outside_front
        # - switch.main_hallway

